# ??????
server.port=8080

# ????????? ????? (mail.ru)
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=demin_921@mail.ru
spring.mail.password=PGh6iiqRQhsjzNGyKqS2
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.mail.ru

app.email.recipient=demin_921@mail.ru

logging.level.com.transpolink=DEBUG